### ISSUE TITLE
Add HD asset support for new MAP files

### ISSUE THREAD

**Issue by 1234567890num** [AntonioDePau/KHPCPatchManager#15]
Any chance .map files can also be supported by this? The problem currently:
1. The area name that pops up when you enter a room is put in separate folder within the `map` folder while in PS2 both the area popup and the map objects/textures are in the same .bar file.
2. All the object model and texture have the same name: `BOB`. I don't know how to differentiate them just from the header.

**Comment by AntonioDePau** [comment]
Something for @o0DemonBoy0o to have a look at, I suppose. Although the map files might be similar to IMDs, where the offset for the texture is always the same?

**Comment by AntonioDePau** [comment]
> Any chance .map files can also be supported by this? The problem currently:
> 
> 1. The area name that pops up when you enter a room is put in separate folder within the `map` folder while in PS2 both the area popup and the map objects/textures are in the same .bar file.
> 2. All the object model and texture have the same name: `BOB`. I don't know how to differentiate them just from the header.

@1234567890num can you provide more info please?
- Game you are trying to mod
- In-game screenshot of what you are trying to mod
- Path and filename of the file you are trying to mod

**Comment by 1234567890num** [comment]
Game: KH2
Path: map/[filename].map (for example `map/hb26.map` with area popup at `map/us/hb26.map`
Screenshot: (using SD .map file)
![portal](https://user-images.githubusercontent.com/53823593/132138648-428f9eb9-4e5a-4c11-bd9f-905ea2c0425f.png)

**Comment by o0DemonBoy0o** [comment]
I don't think you need to have HD asset support for your specific issue (just redo the edits with the PC version of the hb26.map)
but if support would be added for custom ones then all you would need to do is search for the 0x07 identifier in the BAR header
![image](https://user-images.githubusercontent.com/53849249/132276530-7aacd919-1466-4a76-a19f-c887923e72f5.png)

The .map (and a lot of other files) use 0x07 as an identifier for texture info. .maps in this case, use TIMs for textures so you would just run the code the same way you do for .mdlx for .map.
The main issue i see is that .map has multiple different TIMs for all the BOBs in addition to the main map geometry so a scan for each TIM in a map would need to be done.
