### ISSUE TITLE
Wonky Text after editing btltbl.bin

### ISSUE THREAD

**Issue by TrulyTaka** [AntonioDePau/KHPCPatchManager#16]
After editing the btltbl.bin in the original folder of kh1_first, I get this weird text issue..... Actually just creating a mod with this file unaltered causes this text issue
![wonkytext](https://user-images.githubusercontent.com/32620009/133956502-3fe046e8-84b8-40f3-83c6-8bbb290ab08f.PNG)

**Comment by AntonioDePau** [comment]
Not a bug after all?
