### ISSUE TITLE
Patching a.us files reverts certain elements to SD and breaks effects.

### ISSUE THREAD

**Issue by Zurphing** [AntonioDePau/KHPCPatchManager#19]
**Describe the bug:** When trying to patch a.us files from the original/obj folder, the game reverts back to SD and breaks effects of the patched file, causing them to look like squares, or be colored too brightly/lack transparency.

**To Reproduce:** 
1. Grab any a.us file from kh2_sixth/original/obj, in this case I used P_EX100_BTLF.a.us, which corresponds to Valor Form.
2. Create a patch with the proper file structure.
3. Patch in the a.us file.
4. Go in-game, and try attacking using finishing moves/any attack in the form that has a special effect associated with it.

**Expected Behavior:**  
Expected behavior would be that the effects would work just as in the unpatched version of the game, with proper transparency & shapes. Screenshot below is how one of the effects looks in the unpatched game.
![image](https://user-images.githubusercontent.com/72351816/142716131-d06046d0-d30a-4883-9425-7e297340a553.png)

Screenshot of the issue:
![image](https://user-images.githubusercontent.com/72351816/142431689-3a2353c2-1efb-4707-970a-97de27e8569d.png)

**Version used:** v1.15

(Updated to match the format of the issue template, & added a screenshot of how said effect would normally look).

**Comment by AntonioDePau** [comment]
Hey, thanks for reaching out, sorry it took this long to get a reply.
Do you happen to know if this occurs on v1.1.4 too? There have been some changes from 1.1.4 to 1.1.5 to handle some custom assets, and that possibly broke things.

**Comment by Zurphing** [comment]
Hi, absolutely no problem with the wait, 
As it turns out, the issue is present on other versions of the patcher too.
It wasn't linking the a.us files properly to the remastered folder, so it wasn't linking textures to these effects.
It seems DA and Num have been able to fix this, as once you compile Nums fork of OpenKH, 
https://github.com/1234567890num/OpenKh,
(and I believe add what seems to be a missing semicolon to line 117 in Helpers.cs) you can use OpenKH.Command.IDXImg, and properly patch a.us files with the remastered folder, and the effects will play properly in game.

Would it be possible to implement these changes to the OpenKH patcher to KHPCPatchManager?

**Comment by AntonioDePau** [comment]
Yup, on it :) DA (who is actually Num I believe :D) and I have been talking, and he's suggested a fix (and many improvements).
There should be an update for the KHPCPatchManager soon (tests are still on-going, we're checking that there are no new crashes/issues brought by the changes, but there'll always be a risk).
