### ISSUE TITLE
Could not find folder to patch!

### ISSUE THREAD

**Issue by MightyMoose504** [AntonioDePau/KHPCPatchManager#30]
first i am attempting to use this patcher to modify game files installed on a linux system. I cannot drag the patch files to execute via the .exe so i tried launching the patcher and selecting the patches in the gui and when i select the patch and target directory. It then gives me an error stating "Could not find any folder to patch! Make sire you are using the correct path for the "en" folder!

**Comment by AntonioDePau** [comment]
Hey, can you tell me:

- Where you game is installed
- Do you have anything under: C:\Program Files\Epic Games\KH_1.5_2.5\Image\en\

**Comment by liangste332** [comment]
I am getting the same message as MightyMoose504, and it took me a while to find the en folder in C:\Program Files\Epic Games\KH_1.5_2.5\Image\en\. I do not see any option setting to select the path to the en folder when I open the patch manger.

**Comment by liangste332** [comment]
I looked at the instructions for dragging and dropping patches and the en folder regarding the Birth by Sleep Ultimate Mix mod, but I am currently stuck as dragging and dropping the en folder onto the patcher does nothing.

**Comment by AntonioDePau** [comment]
@liangste332, try deleting the C:\Program Files\Epic Games\KH_1.5_2.5\ folder if your game is not installed there.

**Comment by liangste332** [comment]
I don't see how deleting the C:\Program Files\Epic Games\KH_1.5_2.5\ folder will be beneficial becuase that is where my game is installed.

**Comment by AntonioDePau** [comment]
> I don't see how deleting the C:\Program Files\Epic Games\KH_1.5_2.5\ folder will be beneficial becuase that is where my game is installed.

> try deleting the C:\Program Files\Epic Games\KH_1.5_2.5\ folder **if your game is not installed there.**

I never said it would be beneficial if your game was installed there, on the contrary.

Anyway, I'm going to close this issue, because you're already replying in the other one for the exact same issue and the spam is driving me crazy (plus the original user for this issue has not provided additional information, so I assume they found a way to patch the game).
