### ISSUE TITLE
Error when trying to patch Kingdom Hearts DDD

### ISSUE THREAD

**Issue by Azure88** [AntonioDePau/KHPCPatchManager#33]
**Describe the bug**
I got this message when trying to patch Kingdom Hearts Dream Drop Distance.

**To Reproduce**
1. Selected the ddd.txt patch 
2. Selected the instal folder
3. Applying patch

**Expected behavior**
The patch applying

**Screenshots**
![66bcab25-f9f4-4dae-b8b6-a0880d750cf9](https://user-images.githubusercontent.com/48184170/209436405-73c50a48-f3f3-4898-9064-73da3c47cbf8.jpeg)

**Version used (please complete the following information):**
- Version: 1.20

**Affected games (please complete the following information):**
- DDD

**Formats involved (please complete the following information):**
- .txt

**Additional context**

**Comment by AntonioDePau** [comment]
Hey,
> Selected the ddd.txt patch
What do you mean **.txt**? Patches for DDD are in .dddpcpatch format.
Where did you get the patch from?

**Comment by Azure88** [comment]
When I executed the .exe, the resource folder appears and everything inside in .txt

![01](https://user-images.githubusercontent.com/48184170/209438462-afc0a4e0-9217-47cb-b70d-cfd658845986.png)

I can even open them. 

![02](https://user-images.githubusercontent.com/48184170/209438475-547f47b3-7650-40f1-a836-a30fdb96d86a.png)

Is not the correct patch?

**Comment by AntonioDePau** [comment]
Nope, those .txt files contain the list of known file names within the games.
What patch did you want to apply? Some patch from the Nexus website? You need a .dddpcpatch file.
I've made a video guide, you can have a look here: https://www.youtube.com/watch?v=ZfpnishHxDw

**Comment by Azure88** [comment]
I see... Now working properly. Sorry for wasting your time, I'm a new player on PC.

Thanks!!

**Comment by AntonioDePau** [comment]
No problem, enjoy!
