### ISSUE TITLE
If the KH installation folder is not on the C: drive the programm gets stuck on a Browes for folder windown on the desktop.

### ISSUE THREAD

**Issue by TheNightquest** [AntonioDePau/KHPCPatchManager#35]
**Describe the bug**

As the Title says if the installation folder C:\Program Files\Epic Games\KH_1.5_2.5\Image\en\ is not existend or in another drive the patcher doesn't let you search for it. It Opens a "Browes for folder" windown which get's stuck on desktop and cannot acces the other drives.

**To Reproduce**
1. Open Patcher
2. Select a Patch to Apply
3. Click on Apply patch
5. See error

**Expected behavior**
I expect a Normal Browes window to appear, basicly the same that opens when you search the Patch to apply.

**Version used (please complete the following information):**
- Version: v1.2.0.
- 
**Affected games (please complete the following information):**
- I tested KH 1.5 and 2.5

**Additional context**
The line which appears to search for said folder is on row 224. At least this is I think is the part where this happens.
![browes for folder](https://user-images.githubusercontent.com/106732018/213933434-6acc88fd-1ddf-4f61-b7c6-8457b5f25bd4.png)

this is the window that opens when I use it. As you can see desktop, is as far as i can go, the other folders ar just subfolders with no selection of other drives posible.

**Comment by AntonioDePau** [comment]
Hey, that doesn't look like Windows 10, is that Windows 11?
What about those scrollbars, are they fully to the left and top?

**Comment by TheNightquest** [comment]
Hello and thanks for the fast reply and its Win 11 unfortunatly. And yes i am fully up to the top.

**Comment by AntonioDePau** [comment]
Looks like a Windows 11 issue:
- https://learn.microsoft.com/en-us/answers/questions/1068199/issues-with-an-old-net-application-and-windows-11
- https://social.msdn.microsoft.com/Forums/en-US/5a6b4a49-b182-4bad-9fee-0d84dd1905a1/c-folderbrowserdialog-rootfolder-mycomputer-not-functioning-on-windows-10?forum=winforms

Not sure how to fix it tbh. I'm not setting a default path to be opened or anything, so it should give you the option to navigate wherever you need. Are you starting the tool as an admin?

**Comment by TheNightquest** [comment]
hmm, unfortunate. Also yess, i tried it witth and without admin. But thank you for replaying.

**Comment by TheNightquest** [comment]
Uninstalling OneDrive fixes it. deactivating it doesn't help. Only uninstall.

**Comment by AntonioDePau** [comment]
Ah yes, looks like it's OneDrive related indeed:
https://powerusers.microsoft.com/t5/Power-Automate-Desktop/get-file-from-folder-won-t-allow-access-to-folders-that-aren-t/m-p/1892732/highlight/true#M20531

Deactivating Desktop backup maybe?

**Comment by TheNightquest** [comment]
I do some patching right now, I get back to it when Installed these and test that one.

**Comment by TheNightquest** [comment]
Sorry for beiing a little slow. I reinstalled One Drive and unselected the Desktop for backup. I started the Patcher and it loaded the correct Browes for folder. If this happens again then I write another update but this seems to be ok.
