### ISSUE TITLE
KHPC Patch Manager on Steam Deck/Linux

### ISSUE THREAD

**Issue by SoLightTV** [AntonioDePau/KHPCPatchManager#37]
I try to run the Patch manager through Lutris and Steam on deck, itll open for a second then immediately closed. I believe it's a dependency im missing, but im just not sure which one it would be. Any advice/help?

- Version: 1.0.0.8
Epic Games Official Version

**Comment by AntonioDePau** [comment]
Hey, sorry, but the tool is meant to be ran on Windows only.
I don't own a Steam Deck and I have no idea what Lutris is or does, so I have no way to try and reproduce this on my side.

That being said:

- I assume you're trying this with the latest released executable? Have you tried compiling the tool yourself, targetting Linux as the platform?
- I also assume you're "double-clicking" the executable, which tries to open the GUI for the tool, maybe that's something that cannot be done on Linux. Have you tried **running the tool in command** mode through a terminal?

**Comment by RoseIlanga** [comment]
Lutris is a Linux game manager that has integrations with Wine and several game services like Steam.
https://en.wikipedia.org/wiki/Lutris

Here's my output using the latest with .NET 4.0, 4.5, and 4.8, and .NET 5.0 runtime from [here](https://dotnet.microsoft.com/en-us/download/dotnet/5.0) installed.
```
wine KHPCPatchManager.exe
002c:fixme:winediag:loader_init wine-staging 8.18 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0098:fixme:wineusb:query_id Unhandled ID query type 0x5.
0098:fixme:wineusb:query_id Unhandled ID query type 0x5.
0098:fixme:wineusb:query_id Unhandled ID query type 0x5.
0098:fixme:wineusb:query_id Unhandled ID query type 0x5.
0098:fixme:wineusb:query_id Unhandled ID query type 0x5.
012c:err:module:fixup_imports_ilonly mscoree.dll not found, IL-only binary L"KHPCPatchManager.exe" cannot be loaded
012c:err:module:loader_init Importing dlls for L"Z:\\home\\sleetixia\\Downloads\\KHPCPatchManager.exe" failed, status c0000135
```
I'm not sure if there's a winetricks thing I'm missing, but I thought the dotnet ones should have covered it. I get the same error when running in Wine with Mono.

And double-clicking should work just fine for opening graphical programs. It generally works fine for Windows executables run through Wine too as long as they don't have any errors.

**Comment by AntonioDePau** [comment]
Hey @RoseIlanga, I've split this into its own issue: https://github.com/AntonioDePau/KHPCPatchManager/issues/38
Please have a look there.

**Comment by RoseIlanga** [comment]
I can't really find much on this, but it seems like the .NET installers aren't installing the mscoree.dll file for some reason, so .NET programs are failing.

**Comment by RoseIlanga** [comment]
Okay, I commented over there. I should have made it clear I wasn't running through Lutris, though. (I just commented since I wasn't sure if or when the original poster would comment.)

I've also been trying to compile KHPCPatchManager on my computer to see if that works any better, but I've been having trouble with that. I don't know if I should open an issue for that.
