### ISSUE TITLE
Make sure you choose correct 'en'

### ISSUE THREAD

**Issue by renaiku** [AntonioDePau/KHPCPatchManager#41]
![image](https://github.com/AntonioDePau/KHPCPatchManager/assets/17033907/1bc04e7a-9375-4ea8-9b96-65c4413f0a20)

`D:\SteamLibrary\steamapps\common\KINGDOM HEARTS -HD 1.5+2.5 ReMIX-`

There is no folder named 'en' in the `Image` folders.

It happens when applying the french voice patch.

**Comment by Adrien10200** [comment]
I'm having the same issue (Japanese voice patch) even with the latest release

**Comment by AntonioDePau** [comment]
Hey @renaiku and @Adrien10200, sorry, that was indeed my bad. Can you download the executable for release 1.2.1 again? I have deployed a hotfix.

Edit: An easy to spot if you got the incorrect executable is to check the exe's version. If it reads 1.2.0, you'll need to redownload it.
The correct one will have 1.2.1 as the version.

**Comment by Adrien10200** [comment]
It's working perfectly now, thanks @AntonioDePau !

**Comment by AntonioDePau** [comment]
Thanks for confirming. I'll wait for confirmation from @renaiku before closing the issue.

**Comment by renaiku** [comment]
It's working indeed !

Thank you a lot !!!

**Comment by AntonioDePau** [comment]
Sweet :) thanks both for letting me know! Enjoy!
