### ISSUE TITLE
Can't find/paste the installation path on Steam Deck

### ISSUE THREAD

**Issue by EmeraldCraft100** [AntonioDePau/KHPCPatchManager#44]
I have Kingdom Hearts on my Steam Deck, and I've gotten the KHPC Patch Manager running. However, I can't apply a patch because it says it can't find the installation path. And when I tried pasting the full path to the dt folder, it gave me this error;
![image](https://github.com/AntonioDePau/KHPCPatchManager/assets/172912070/a72041c4-35d5-47d6-b809-63768acc8b45)
My path is: /home/deck/.local/share/Steam/steamapps/common/KINGDOM HEARTS -HD 1.5+2.5 ReMIX-/Image/dt
Is this an incorrect path?

**Comment by AntonioDePau** [comment]
Hey @EmeraldCraft100, what do you mean "pasting"? Are you using the GUI mode, or the command line interface mode?
GUI mode should let you browse for the installation folder manually, while CLI mode would have you type/paste/drag&drop the path.

**Comment by EmeraldCraft100** [comment]
I copied the file location in the file explorer (Dolphin).
Not that it matters now, though,, because I asked a friend, and he managed to find a workaround.
Specifically, he had a game downloaded on the desktop, then cut and pasted KH 1.5+2.5 onto it, and redownloaded it to the desktop.
However, the KHPC Patch Manager has a tendency to crash whenever I opened any other .exe file.

**Comment by julianrios** [comment]
Facing the same issue. For me I can navigate to the folder not sure if its because its hidden
![Screenshot_20240620_203206](https://github.com/AntonioDePau/KHPCPatchManager/assets/47252650/138a9d09-764f-4fb9-98ad-02be391ec7ac)

My file location is here but the gui only accepts \ 

So I tried to pass as this:
Z:\home\deck\.local\share\Steam\steamapps\common\KINGDOM HEARTS -HD 1.5+2.5 ReMIX-\Image\dt

Deck Location:
/home/deck/.local/share/Steam/steamapps/common/KINGDOM HEARTS -HD 1.5+2.5 ReMIX-/Image/dt

**Comment by TheFervidActor** [comment]
> Facing the same issue. For me I can navigate to the folder not sure if its because its hidden ![Screenshot_20240620_203206](https://private-user-images.githubusercontent.com/47252650/341600405-138a9d09-764f-4fb9-98ad-02be391ec7ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MzA0NzIsIm5iZiI6MTcxODkzMDE3MiwicGF0aCI6Ii80NzI1MjY1MC8zNDE2MDA0MDUtMTM4YTlkMDktNzY0Zi00ZmI5LTk4YWQtMDJiZTM5MWVjN2FjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDAwMzYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYjY0ZTQwNzk2NzQ1MjQ4NzgzOWNjZmJmMjY3ODdlYTQzYjg3MjE2NTBmMTczMDcwYjM4YzkwZTBkMzczNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NfIjTAbtx_NNPHZVa4ZJGGUy9drSNHkmhTrLqC7bpfs)
> 
> My file location is here but the gui only accepts \
> 
> So I tried to pass as this: Z:\home\deck.local\share\Steam\steamapps\common\KINGDOM HEARTS -HD 1.5+2.5 ReMIX-\Image\dt
> 
> Deck Location: /home/deck/.local/share/Steam/steamapps/common/KINGDOM HEARTS -HD 1.5+2.5 ReMIX-/Image/dt

use luxwine to launch the exe. I had no issues locating the game in its usual location. The default wine won't find it.

**Comment by julianrios** [comment]
Seems my deck folder is hidden is there a way to unhide this in the wine settings? 
![Screenshot_20240620_213938](https://github.com/AntonioDePau/KHPCPatchManager/assets/47252650/05f78b91-b75e-4206-a2c2-02724b29794c)

**Comment by TheFervidActor** [comment]
Did you check all the Letters? Your kH game is usually under one of them. Ok. Create a link to your common folder(where your games are installed and put it in your downloads folder(or whatever folder you can find super easy). from there, it's a matter of clicking on it and it'll send you to your common folder

**Comment by julianrios** [comment]
Thanks I was able to get this working. I ended up just doing a factory reset on my steam deck since the main folder I needed to get who was hidden once I did that I was able to get everything working.
