### ISSUE TITLE
1.2.1 executable cannot run

### ISSUE THREAD

**Issue by ruliruli12** [AntonioDePau/KHPCPatchManager#45]
Version 1.2.1 of KHPCPatchManager.exe does not run. Yes, I can download it but when I run it both normally and "as administrator" it simply does not work. I have tried previous versions and it does open, I put the patch I want, but then when I apply it it does not find the correct path, it asks me to choose the folder where the game is located, but it does not recognize it either, I imagine that because my version is STEAM and previous patches will only work with EPIC. That's why I downloaded the latest version, but it doesn't open and I don't know what to do. Emphasize that I use Windows 10 (same message but in English haha)

**Comment by ruliruli12** [comment]
Version 1.2.1 of KHPCPatchManager.exe does not run. Yes, I can download it but when I run it both normally and "as administrator" it simply does not work. I have tried previous versions and it does open, I put the patch I want, but then when I apply it it does not find the correct path, it asks me to choose the folder where the game is located, but it does not recognize it either, I imagine that because my version is STEAM and previous patches will only work with EPIC. That's why I downloaded the latest version, but it doesn't open and I don't know what to do. Emphasize that I use Windows 10 (same message but in English haha)

**Comment by AntonioDePau** [comment]
What happens when you try to run it? Does it open and close instantly? Does it not open at all?
Do any processes of KHPCPatchManager appear in your task manager?

Have you tried running the executable in both GUI and CLI modes?
To start the tool in GUI mode, simply double-click on it.
To start the tool in CLI mode, drag and drop a .khpcpatch file onto it.

Additionally, please start the exe from CMD or Powershell in case an uncaught exception is occuring, so that you can share the error message here.

**Comment by ruliruli12** [comment]
Al hacer doble click o al abrir como administrador no se abre en absoluto, simplemente parece que algo carga durante menos de un segundo y después no ocurre nada, en la barra de tareas si que aparece algo que enseguida se cierra. Respecto a las posibles soluciones que me ofreces, no las entiendo muy bien porque soy un novato en estas cosas. ¿Podrias explicar más en profundidad eso de CLI, CMD o Powershell?

**Comment by ruliruli12** [comment]
Al pulsar click derecho y buscar "Problemas de compatibilidad" puedo ejecutar el archivo y esto es lo que aparece
![Error](https://github.com/AntonioDePau/KHPCPatchManager/assets/173142729/5c63e5e1-249e-422e-ac99-43b8ade707a7)

**Comment by AntonioDePau** [comment]
You're getting an access denied error related to the system32 folder. This is not an issue with the tool but with how your machine is setup or with your account permissions.

Please check that you have admin privileges (regardless of whether you are running the tool in admin mode or not) and that you can access the route that is causing the access denied error.

Also please stop commenting in any language other than English. The issues and comments posted here need to be readable by the whole community. If you cannot communicate in English any further, please reach out to me on Discord.
