### ISSUE TITLE
Could not find "\image\en" with my steam version

### ISSUE THREAD

**Issue by masejr95** [AntonioDePau/KHPCPatchManager#46]
![Screenshot 2024-06-18 125706](https://github.com/AntonioDePau/KHPCPatchManager/assets/173192696/3e992ef6-62cd-4d2d-89c0-9797543da471)

**Comment by masejr95** [comment]
Nevermind fixed it

**Comment by AntonioDePau** [comment]
Care to mention how you fixed it...?

**Comment by masejr95** [comment]
just re-installed this in the same hard drive folder as the game, had an internet glitch and the file was not the updated version.
