### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by MochaMoa** [AntonioDePau/KHPCPatchManager#47]
When I open the KHPCPatchManager_MSBUILD batch file I get this message "The system cannot find the path specified." with no other options. I can't find where to set the directory. I'm using the steam release on Windows 10. 

![image](https://github.com/AntonioDePau/KHPCPatchManager/assets/42686309/bec58d8b-3b98-45a6-baf8-de3a9163c14c)

**Comment by AntonioDePau** [comment]
Hey, what are you attempting to do?
The MSBUILD file is meant to be used for developers who want to compile the tool from its source code.

If you are a user who simply wants to use the KHPCPatchManger tool, download and launch the lastest compiled binary (executable): https://github.com/AntonioDePau/KHPCPatchManager/releases/download/v1.2.1/KHPCPatchManager.exe

**Comment by MochaMoa** [comment]
Oh my gosh I'm so goofy. Thank you so much, that was instantly it. I have no idea how I missed that!

Literally me
![maxresdefault-1](https://github.com/AntonioDePau/KHPCPatchManager/assets/42686309/11716f49-36ee-4c68-8b17-0d33a54c8294)
