### ISSUE TITLE
Cannot find the exe

### ISSUE THREAD

**Issue by ghost** [AntonioDePau/KHPCPatchManager#51]
Every tutorial, including your own, says "just drop into the exe". But there isn't one anywhere in this. There's a BAT file that doesn't work.

**Comment by AntonioDePau** [comment]
For people who might have been having the same issue, I'm assuming this was because you were downloading the whole branch's code instead of the released exe that can be found within the actual release: https://github.com/AntonioDePau/KHPCPatchManager/releases/tag/v1.2.1

**Comment by AntonioDePau** [comment]
@justsquigglez, let me know if you want me to delete the issue altogether.
